### ISSUE TITLE
Fix SRL support (DSiWare)

### ISSUE THREAD

**Issue by PokeAcer549** [AdmiralCurtiss/WfcPatcher#15]
Hey Admiral,
Due to new advances in the 3DS hacking scene, we can now make and use DSiWare CIAs out of either NDSes obtained from 'sources' or from SRLs via NUS. I tried to patch Flipnote Studio to remove the HTTPS NAS connections, but it didnt work and the file just crashed when it tried to load. 
It's probable you do, but if you do not know how to download from DSi NUS, just get the dsikey (I can provide it via PM), place it in a BIN file named dsikey.bin, and copy that into a directory where the Wii NUS Downloader is. Then, it shall detect that key, and you can then decrypt the files to APP (which are SRL files).

**Comment by the4anoni** [comment]
For Flipnote Studio Dsi i found this http://www.sudomemo.net/

**Comment by the4anoni** [comment]
I have 2 dsi one with 1.4.4 fw and other one with 1.4.5 so i can help :) But i don't have any 3ds with cfw (i don't piracy 3ds games)

**Comment by PokeAcer549** [comment]
...I know what Sudomemo is, I just dont want to have to add a proxy server and change it whenever I want to use Wiimmfi, so I'd rather a HTTP patch and then a DNS change so I can use Wiimmfi.

**Comment by PokeAcer549** [comment]
OK; this is just my own idiocy:
@AdmiralCurtiss it still does it, it just complains (ensure users wait until it finishes!)
