### ISSUE TITLE
.exe can't run

### ISSUE THREAD

**Issue by Hawnken** [AdmiralCurtiss/WfcPatcher#18]
Hello, when I click on WfcPatcher.exe for use, the black board (board of command) it opens but closes immediately.
Same problem when I try open in "Administrator mode".

I'm sorry for my bad english.

OS : Windows 10
Update : 1.6

**Comment by AdmiralCurtiss** [comment]
It's a command line application. Launch it from the command line, or just drag-and-drop your files to patch onto it.
