### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by randompokemonplayer** [AdmiralCurtiss/WfcPatcher#19]
i used the 1.6 on some of my games and now i have 2 versions 1 of wich is my old game wich has saved data. and rhe second one with working online how do i transfer my saved data to my online working rom.

**Comment by AdmiralCurtiss** [comment]
This has little to do with this tool, but... just transfer the save file from your old game to your new game. On most flash cards or emulators that would be a `*.sav` file matching the filename of the game itself. Just rename it to match the new game filename.
