### ISSUE TITLE
Version 1.5: Pokemon Platinum (Spanish) can't be patched.

### ISSUE THREAD

**Issue by eltanoDC** [AdmiralCurtiss/WfcPatcher#4]
![pokemon platino no parchea](https://cloud.githubusercontent.com/assets/7727469/7443133/78bcc058-f10c-11e4-86eb-53c8e7053d36.jpg)

I'm having an issue with Pokemon Platinum, using the newest version of the patcher. As you can see in the screen capture I sent you, it says that is hasn't found anything to patch.

**Comment by AdmiralCurtiss** [comment]
e:\wfcpatcher>WfcPatcher.exe "Pokemon - Edicion Platino (Spain).nds"
    Reading and copying Pokemon - Edicion Platino (Spain).nds...
    Patching ARM Executables...
    Patching Overlays...
    Replacing overlay 4...
    Patched to Pokemon - Edicion Platino (Spain) (AltWfc).nds!

Can't confirm. Try redumping your game with WoodDumper, it should match: http://datomatic.no-intro.org/?page=show_record&s=28&n=3787
