### ISSUE TITLE
AC:WW - Pure white screen

### ISSUE THREAD

**Issue by PokeAcer549** [AdmiralCurtiss/WfcPatcher#6]
Hi,
I've patched my PAL ROM for AC:WW, yet when I run it on my R4 it hits a pure white screen - not even the 'nintendo' logo, and I have to restart DS. Know why?

**Comment by PokeAcer549** [comment]
Fixed - Use NTSC-U v1.1 ROM.
PAL ROM still not working

**Comment by AdmiralCurtiss** [comment]
Should probably check this out anyway.

**Comment by AdmiralCurtiss** [comment]
Works fine here with a dump matching these checksums: http://datomatic.no-intro.org/?page=show_record&n=0389&s=28

Presumably either a bad dump or the R4 causing problems.
