### ISSUE TITLE
Make a --domain functionality

### ISSUE THREAD

**Issue by PokeAcer549** [AdmiralCurtiss/WfcPatcher#8]
Like the wiimmfi patcher, which you can use to patch a game with a certain domain (Like I made BeanJrFi do), maybe add this type of thing to the patcher so instead of patching just http, patch http and the domain.

**Comment by AdmiralCurtiss** [comment]
Seems reasonable, sure.

**Comment by PokeAcer549** [comment]
Thanks :stuck_out_tongue: 
I'd do it myself but I know 0% of C.

**Comment by PokeAcer549** [comment]
I see you've added this - I'll test it now

**Comment by AdmiralCurtiss** [comment]
Yeah I haven't gotten around to actually testing it, so it's not in master yet. You have to compile https://github.com/AdmiralCurtiss/WfcPatcher/tree/wip if you want to try it.

**Comment by PokeAcer549** [comment]
Thankfully I has VS2012 from my school - I'll compile and test, though the arm9-* files from the commit https://github.com/AdmiralCurtiss/WfcPatcher/commit/3a41995c319759180829a5089d94befda6743df7
annoys me xD
