### ISSUE TITLE
Error with patching Beyblade Metal Masters !!!

### ISSUE THREAD

**Issue by the4anoni** [AdmiralCurtiss/WfcPatcher#9]
It says: 
Make sure is this game have wfc !

**Comment by Prof9** [comment]
As noted in Prof9/wfcreplay#19, this game does not actually appear to have WFC functionality despite the WFC logo on the boxart. Only the North American version has this, which was published by Konami, whereas it was published by Hudson in all other regions.

**Comment by the4anoni** [comment]
This game support Wfc !!!
'' It features over 30 characters to play as, 37 characters to battle, and 2-player versus mode via Nintendo Wi-Fi Connection.''
Source: http://beyblade.wikia.com/wiki/Beyblade:_Metal_Masters_(video_game)

**Comment by AdmiralCurtiss** [comment]
Yeah as far as I can tell this doesn't actually have WFC support. Closing this, feel free to reopen if you can prove (in-game screenshots/videos) that it does.
